# PyCox as Module

In [2]:
import numpy as np
from chv1r6180 import *
import json

Weyl 群基本操作

In [3]:
W = coxeter("A", 5)
print('Group Order:', W.order)
print('Cartan Matrix: \n', np.array(W.cartan))
print('roots: \n', W.roots)

Group Order: 720
Cartan Matrix: 
 [[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]
roots: 
 [(1, 0, 0, 0, 0), (0, 1, 0, 0, 0), (0, 0, 1, 0, 0), (0, 0, 0, 1, 0), (0, 0, 0, 0, 1), (1, 1, 0, 0, 0), (0, 1, 1, 0, 0), (0, 0, 1, 1, 0), (0, 0, 0, 1, 1), (1, 1, 1, 0, 0), (0, 1, 1, 1, 0), (0, 0, 1, 1, 1), (1, 1, 1, 1, 0), (0, 1, 1, 1, 1), (1, 1, 1, 1, 1), (-1, 0, 0, 0, 0), (0, -1, 0, 0, 0), (0, 0, -1, 0, 0), (0, 0, 0, -1, 0), (0, 0, 0, 0, -1), (-1, -1, 0, 0, 0), (0, -1, -1, 0, 0), (0, 0, -1, -1, 0), (0, 0, 0, -1, -1), (-1, -1, -1, 0, 0), (0, -1, -1, -1, 0), (0, 0, -1, -1, -1), (-1, -1, -1, -1, 0), (0, -1, -1, -1, -1), (-1, -1, -1, -1, -1)]


## Left cell equivalence

以 F4 为例，找到 Left cell 划分

In [4]:
W = coxeter("F", 4)
klcells_info = klcells(W, 1, v)
print('Partition Numbers:', len(klcells_info[0]))
#print(klcells_info[0])

Partition Numbers: 72


确定其中一个 left cell (第 60 个)，输出 left cell 中所有元素

In [5]:
elm_list = klcells_info[0][60]
print('Length:', len(elm_list))
print(elm_list)

Length: 9
[[1, 3, 2, 1], [0, 1, 3, 2, 1], [2, 1, 3, 2, 1], [0, 2, 1, 3, 2, 1], [1, 2, 1, 3, 2, 1], [1, 0, 2, 1, 3, 2, 1], [0, 1, 2, 1, 3, 2, 1], [2, 1, 0, 2, 1, 3, 2, 1], [3, 2, 1, 0, 2, 1, 3, 2, 1]]


以该 left cell 中第一个群元为例， klcellrepelm 输出该群元所在 left cell 信息

In [6]:
print(klcellrepelm(W, [1, 3, 2, 1]))

{'size': 9, 'character': [['9_1', 1]], 'a': 2, 'special': '9_1', 'index': 22, 'elms': False, 'distinv': False}


用 left cell 找到 left cell 所有元素

In [7]:
elms = leftcellelm(W, [1, 3, 2, 1])['elms']
print(elms)

{(37, 22, 36, 2), (13, 32, 12, 33), (46, 13, 3, 2), (13, 15, 36, 2), (15, 46, 16, 2), (15, 4, 40, 18), (37, 4, 12, 33), (22, 39, 3, 2), (15, 4, 2, 42)}


转换为置换形式

In [8]:
for elm in elms:
    print(W.coxelmtoword(elm))


[0, 2, 1, 3, 2, 1]
[1, 3, 2, 1]
[0, 1, 2, 1, 3, 2, 1]
[2, 1, 3, 2, 1]
[1, 0, 2, 1, 3, 2, 1]
[2, 1, 0, 2, 1, 3, 2, 1]
[0, 1, 3, 2, 1]
[1, 2, 1, 3, 2, 1]
[3, 2, 1, 0, 2, 1, 3, 2, 1]


确实是第 60 个 left cell 中所有元素

选取任意 F4 Weyl Group 中元素，计算所在 left cell

In [9]:
w = [2, 1, 3, 0, 2]
W.reducedword(w, W)
elms = leftcellelm(W, w)['elms']
for elm in elms:
    print(W.coxelmtoword(elm))

[1, 2, 1, 0, 3, 2]
[1, 0, 2]
[2, 1, 0, 2]
[0, 3, 2]
[1, 0, 3, 2]
[3, 2, 1, 0, 2]
[0, 2]
[2, 1, 0, 3, 2]
[0, 1, 2, 1, 0, 3, 2]


Chartable

In [10]:
char_table = chartable(W)
print(char_table.keys())

dict_keys(['charnames', 'classnames', 'classlengths', 'classreps', 'b', 'a', 'irreducibles', 'position_id', 'position_sgn', 'position_refl', 'permsgn'])


Test of Kl polynomials function (Explore two-sided cell)

In [11]:
# kl_polynomials = klpolynomials(W, 1, v)
# print(kl_polynomials['elms'])

## Figure out the exact effect of generators

In [12]:
W1 = coxeter('B', 4)
W1.roots[:16]

[(1, 0, 0, 0),
 (0, 1, 0, 0),
 (0, 0, 1, 0),
 (0, 0, 0, 1),
 (1, 1, 0, 0),
 (0, 1, 1, 0),
 (0, 0, 1, 1),
 (2, 1, 0, 0),
 (1, 1, 1, 0),
 (0, 1, 1, 1),
 (2, 1, 1, 0),
 (1, 1, 1, 1),
 (2, 2, 1, 0),
 (2, 1, 1, 1),
 (2, 2, 1, 1),
 (2, 2, 2, 1)]

This does not correspond to root system we are familiar with. So we recreate the Coxeter system using Cartan matrix of B4, and take true basis into account.

In [13]:
import numpy as np
W2 = coxeter([[2, -1, 0, 0], 
              [-1, 2, -1, 0], 
              [0, -1, 2, -1], 
              [0, 0, -2, 2]])
W2.roots[:16] # original roots

[(1, 0, 0, 0),
 (0, 1, 0, 0),
 (0, 0, 1, 0),
 (0, 0, 0, 1),
 (1, 1, 0, 0),
 (0, 1, 1, 0),
 (0, 0, 1, 1),
 (1, 1, 1, 0),
 (0, 1, 1, 1),
 (0, 0, 1, 2),
 (1, 1, 1, 1),
 (0, 1, 1, 2),
 (1, 1, 1, 2),
 (0, 1, 2, 2),
 (1, 1, 2, 2),
 (1, 2, 2, 2)]

Taking basis (Simple roots) into account

In [14]:
def test_roots(basis, roots):
    new_roots = []
    for root in roots:
        s = np.zeros(len(root))
        for i in range(len(root)):
            s += root[i] * basis[i]
        new_roots.append(s)
    return np.array(new_roots,dtype=np.int8)
# B4 basis
basis = np.array([[1,-1,0,0],
                  [0,1,-1,0],
                  [0,0,1,-1],
                  [0,0,0,1]])
test_roots(basis, W2.roots[:16])

array([[ 1, -1,  0,  0],
       [ 0,  1, -1,  0],
       [ 0,  0,  1, -1],
       [ 0,  0,  0,  1],
       [ 1,  0, -1,  0],
       [ 0,  1,  0, -1],
       [ 0,  0,  1,  0],
       [ 1,  0,  0, -1],
       [ 0,  1,  0,  0],
       [ 0,  0,  1,  1],
       [ 1,  0,  0,  0],
       [ 0,  1,  0,  1],
       [ 1,  0,  0,  1],
       [ 0,  1,  1,  0],
       [ 1,  0,  1,  0],
       [ 1,  1,  0,  0]], dtype=int8)

## Testing Coxeter Group Elements

In [15]:
def root_to_cord(basis_cord, root):
    s = np.zeros(len(root))
    for i in range(len(root)):
        s += root[i] * basis[i]
    return s

for gen_index in range(4):
    print(f"The effect generator s_{gen_index}")
    cox_elm = W2.wordtocoxelm([gen_index])
    for i in range(len(cox_elm)):
        old_cord = root_to_cord(basis, W2.roots[i])
        new_cord = root_to_cord(basis, W2.roots[cox_elm[i]])
        print(f"Sending {old_cord} to {new_cord}")

The effect generator s_0
Sending [ 1. -1.  0.  0.] to [-1.  1.  0.  0.]
Sending [ 0.  1. -1.  0.] to [ 1.  0. -1.  0.]
Sending [ 0.  0.  1. -1.] to [ 0.  0.  1. -1.]
Sending [0. 0. 0. 1.] to [0. 0. 0. 1.]
The effect generator s_1
Sending [ 1. -1.  0.  0.] to [ 1.  0. -1.  0.]
Sending [ 0.  1. -1.  0.] to [ 0. -1.  1.  0.]
Sending [ 0.  0.  1. -1.] to [ 0.  1.  0. -1.]
Sending [0. 0. 0. 1.] to [0. 0. 0. 1.]
The effect generator s_2
Sending [ 1. -1.  0.  0.] to [ 1. -1.  0.  0.]
Sending [ 0.  1. -1.  0.] to [ 0.  1.  0. -1.]
Sending [ 0.  0.  1. -1.] to [ 0.  0. -1.  1.]
Sending [0. 0. 0. 1.] to [0. 0. 1. 0.]
The effect generator s_3
Sending [ 1. -1.  0.  0.] to [ 1. -1.  0.  0.]
Sending [ 0.  1. -1.  0.] to [ 0.  1. -1.  0.]
Sending [ 0.  0.  1. -1.] to [0. 0. 1. 1.]
Sending [0. 0. 0. 1.] to [ 0.  0.  0. -1.]


We can conclude that $s_0=(1,2)$, $s_1=(2,3)$, $s_2=(3,4)$, $s_3=(4,-4)$.
Equivalently, $s_0=(2,1,3,4)$, $s_1=(1,3,2,4)$, $s_2=(1,2,4,3)$, $s_3=(1,2,3,-4)$

Use lieToolbox to tackle signed perm computation

In [16]:
from weight import WeylGroupElement
def word_to_weylgroupelm(word, len_n):
    wg = WeylGroupElement(list(range(1,len_n+1)))
    for s in word:
        entry_next = list(range(1, len_n+1))
        if s == len_n - 1:
            entry_next[len_n-1] = -(len_n)
        else:
            entry_next[s], entry_next[s+1] = s+2, s+1
        wg_next = WeylGroupElement(entry_next)
        wg = wg * wg_next
        #print(wg_next)
    return wg

def cycle_to_gen(cycle, max_num):
    # represent (1,n) by (i, i+1) resursive
    def twocycle_to_gen(p):
        n = p[1]
        if n <= 2:
            return [0]
        return twocycle_to_gen((1, n-1)) + [n-2] + twocycle_to_gen((1, n-1))
    
    prod = []
    if len(cycle) == 2 and cycle[0] == -cycle[1]:
        num = abs(cycle[0])
        if num == max_num:
            prod.append((max_num, -max_num))
        elif num == 1:
            prod.extend([(1, max_num), (max_num, -max_num), (1, max_num)])
        else:
            prod.extend([(1, num), (1, max_num), (1, num),
                     (max_num, -max_num), 
                     (1, num), (1, max_num), (1, num)])
            # print(prod)
    else:
        num0 = cycle[0]
        if num0 == 1:
            for num1 in cycle[1:]:
                prod.append((1, num1))
        else:
            for num1 in cycle[1:]:
                if num1 == 1:
                    prod.append((1, num0))
                elif num1 == num0 + 1 or num1 == num0 - 1:
                    prod.append((num0, num1))
                else:
                    prod.extend([(1, num0), (1, num1), (1, num0)])
    
    # (1,n) to generators
    new_prod = []
    for cycle in prod:
        if cycle[0] == cycle[1] + 1 or cycle[0] == cycle[1] - 1:
            new_prod.append(min(cycle)-1)
        elif cycle[0] + cycle[1] == 0:
            new_prod.append(max_num-1)
        else:
            new_prod.extend(twocycle_to_gen(cycle))
    
    return new_prod


def weylgroupelm_to_word(entry: list):
    disjoint_cycles = []
    n = len(entry)
    entry0 = list(range(1, n+1))
    
    signed_term = []
    for index in range(n):
        num = entry[index]
        if num < 0:
            signed_term.append([-num, num])
            entry[index] = -num
        
    # same procedure as symmetry group
    while entry0:
        # get a cycle
        cycle = []
        index = 0
        index_list = [0]
        cycle.append(entry[index])
        while entry[entry0.index(entry[index])] != entry[0]:
            index = entry0.index(entry[index])
            index_list.append(index) # keep a list of index
            cycle.append(entry[index])
        # add the cycle to prod
        if len(cycle) > 1:
            disjoint_cycles.append(cycle)
        # delete the cycle from entry
        index_list.sort(reverse=True)
        for index in index_list:
            entry.pop(index)
            entry0.pop(index)
    
    disjoint_cycles.extend(signed_term)
    
    # disjoint cycles to gen
    prod = []
    print(disjoint_cycles)
    for cycle in disjoint_cycles:
        prod.extend(cycle_to_gen(cycle, n))
    # print(prod)
    return W2.reducedword(prod, W2)

word = [0, 1, 0, 2, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0]
word_re = W2.reducedword(word, W2)
print(word_re)
print(word_to_weylgroupelm(word, 4))
print(word_to_weylgroupelm(word_re, 4))
print(word_to_weylgroupelm(weylgroupelm_to_word([1,-3,-2,-4]), 4))
print(weylgroupelm_to_word(word_to_weylgroupelm([0,1,0,2,1,3,0], 4).entry))

[0, 1, 2, 3, 2, 1, 0]
[-1, 2, 3, 4] lieType: B
[-1, 2, 3, 4] lieType: B
[[3, 2], [3, -3], [2, -2], [4, -4]]
[1, -3, -2, -4] lieType: B
[[4, 1], [3, 2], [4, -4]]
[0, 1, 0, 2, 1, 0, 3]


In [17]:
from weight import Weight, HighestWeightModule
lbd = Weight([-3.5, 2.5, 1.5], 'B')
L = HighestWeightModule(lbd)
gkdim0 = L.GKdim()
print(gkdim0)
lbd_antido = lbd.getAntidominant()
wg = lbd.getWeylGroupElement(lbd, lbd_antido)
print(wg)
wd = weylgroupelm_to_word(wg.entry)
print(wd)
elms = leftcellelm(W2, wd)
print(elms)


5
[-1, -2, 3] lieType: B
[[1, -1], [2, -2]]
[1, 2, 1, 0]
{'size': 8, 'a': 3, 'character': [['[[2, 1], [1]]', 1]], 'special': '[[2, 1], [1]]', 'index': 15, 'elms': {(12, 31, 1, 6), (5, 12, 30, 6), (21, 15, 30, 6), (21, 1, 20, 10), (21, 1, 14, 26), (5, 18, 20, 10), (21, 16, 4, 6), (5, 18, 14, 26)}, 'distinv': '01210'}


In [29]:
WE6 = coxeter('E', 6)
longest_perm = longestperm(WE6)
longest_perm_as_wd = WE6.permtoword(longest_perm)
print(longest_perm_as_wd)






[0, 1, 2, 0, 3, 1, 2, 0, 3, 2, 4, 3, 1, 2, 0, 3, 2, 4, 3, 1, 5, 4, 3, 1, 2, 0, 3, 2, 4, 3, 1, 5, 4, 3, 2, 0]


In [36]:
left_cell_infos = klcellreps(WE6)

In [41]:
from chv1r6180 import *
left_cell_infos = klcellreps(WE6)
for left_cell_info in left_cell_infos:
    if left_cell_info['a'] == 11:
        print(f"Index: {left_cell_info['index']}")

for elm in left_cell_infos[13]['elms']:
    print(WE6.coxelmtoword(elm))

Index: 13
[0, 3, 1, 2, 0, 4, 5, 4, 3, 1, 2, 0, 3, 2, 4, 3, 1, 5, 4, 3]
[1, 2, 0, 3, 1, 2, 3, 4, 3, 2, 5, 4, 3, 1, 2, 0, 3, 4, 5]
[0, 1, 2, 0, 3, 2, 4, 3, 2, 5, 4, 3, 1, 2, 0, 3, 4, 5]
[0, 1, 2, 0, 3, 2, 0, 4, 3, 1, 2, 0, 3, 4, 5, 4, 3, 1]
[0, 1, 2, 3, 2, 4, 3, 1, 2, 0, 3, 4, 5, 4, 3, 1]
[0, 3, 4, 3, 1, 2, 0, 5, 4, 3, 1, 2, 0, 3, 2, 4, 3, 1, 5, 4, 3]
[2, 3, 2, 4, 3, 2, 5, 4, 3, 1, 2, 0, 3, 4, 5]
[0, 2, 3, 1, 2, 0, 3, 4, 3, 1, 5, 4, 3, 1]
[1, 2, 3, 2, 4, 3, 1, 2, 0, 3, 4, 5, 4, 3, 1]
[0, 2, 0, 3, 2, 0, 4, 3, 1, 2, 0, 3, 4, 5, 4, 3, 1]
[0, 1, 2, 0, 4, 5, 4, 3, 1, 2, 0, 3, 2, 4, 3, 1, 5, 4, 3]
[1, 2, 0, 3, 1, 2, 0, 3, 2, 4, 3, 2, 5, 4, 3, 1, 2, 0, 3, 4, 5]
[0, 1, 3, 1, 4, 3, 1, 5, 4, 3, 1]
[0, 1, 3, 1, 2, 0, 4, 5, 4, 3, 1, 2, 0, 3, 2, 4, 3, 1, 5, 4, 3]
[0, 1, 3, 1, 2, 0, 4, 3, 1, 2, 0, 3, 2, 4, 3, 1, 5, 4, 3, 1]
[1, 3, 1, 2, 3, 4, 3, 1, 2, 0, 3, 4, 5, 4, 3, 1]
[2, 0, 3, 1, 2, 0, 3, 2, 4, 3, 1, 2, 0, 3, 4, 5, 4, 3, 1]
[0, 1, 3, 1, 2, 0, 3, 2, 4, 3, 1, 2, 0, 3, 4, 5, 4, 3, 1]
[0, 1, 2, 0, 3,